/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DicomServerHandle {
  get localPort(): number
  /**
   * Stops accepting new associations and waits for the listener to shut down. Associations
   * already in progress finish independently (or hit their own idle timeout) - this does not
   * interrupt them. Safe to call more than once.
   */
  close(): void
}

/**
 * Reports whether a file looks like valid DICOM. Mirrors `dcmnorm
 * --check-dicom`.
 */
export declare function checkDicom(filePath: string): Promise<unknown>

/**
 * Performs a C-ECHO (DICOM Verification) against `destination` ("host:port"). Resolves with the
 * response Status code (0 = success); rejects only if the association itself could not be
 * established (unreachable host, no accepted presentation context, etc). `onLog`, if given, is
 * called (synchronously, no return value expected) with a debug line for each notable DIMSE
 * event - association open/close, the request sent, the response received.
 */
export declare function echoScu(destination: string, options?: EchoScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): Promise<unknown>

export interface EchoScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  timeoutMs?: number
}

/**
 * Sets/removes DICOM attributes, optionally stripping private tags. Mirrors
 * `dcmnorm --set KEY=VALUE --remove KEY --remove-private-tags`. Writes back
 * to `file_path` in place unless `options.output_path` is given.
 */
export declare function editTags(filePath: string, options?: EditTagsOptions | undefined | null): Promise<unknown>

export interface EditTagsOptions {
  outputPath?: string
  set?: Record<string, string>
  remove?: Array<string>
  removePrivateTags?: boolean
}

/**
 * Performs a C-FIND (Study Root Query/Retrieve) against `destination` ("host:port"). `query`
 * values: empty string is a universal-match "return key" (mirrors findscu's bare `-k TAG`),
 * non-empty constrains the match (mirrors `-k TAG=value`); `QueryRetrieveLevel` defaults to
 * `"STUDY"` if not given. Resolves with one flat/hex-keyed DICOM JSON string per match (parse
 * JS-side, same shape as `readJson({format: "flat", keyStyle: "hex"})`). `onLog`, if given, is
 * called (synchronously, no return value expected) with a debug line for each notable DIMSE
 * event - association open/close, and each C-FIND-RQ/RSP (query values are not logged, only the
 * tag keys queried, since the Identifier commonly carries PHI).
 */
export declare function findScu(destination: string, query: Record<string, string>, options?: FindScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): Promise<unknown>

export interface FindScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  maxPduLength?: number
  timeoutMs?: number
}

/**
 * Performs a C-MOVE (Study Root Query/Retrieve), asking `destination` ("host:port") to push
 * `studyInstanceUid` to `moveDestinationAe` (an AE title `destination` already knows how to
 * reach, not a socket address). Blocks until the move reaches a terminal status; resolves with
 * that terminal status and sub-operation counts regardless of success/warning/failure - the
 * caller decides what's retryable, this only rejects if the association itself failed. `onLog`,
 * if given, is called (synchronously, no return value expected) with a debug line for each
 * notable DIMSE event - association open/close, and each C-MOVE-RQ/RSP (including every pending
 * response, so a slow multi-instance move is visible sub-operation by sub-operation).
 */
export declare function moveScu(destination: string, moveDestinationAe: string, studyInstanceUid: string, options?: MoveScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): Promise<unknown>

export interface MoveScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  maxPduLength?: number
  /** Absolute ceiling (connect through release) for the whole call - not reset by activity. */
  timeoutMs?: number
  /**
   * Directory to watch for local write progress (e.g. this retrieve's own cache destination)
   * - see `staleDataTimeoutMs`. Both must be set for the watch to run.
   */
  watchPath?: string
  /**
   * How long `watchPath` may go without a new/modified file before the connection is
   * considered stale and aborted - independent of, and typically much shorter than,
   * `timeoutMs`.
   */
  staleDataTimeoutMs?: number
}

export interface MoveScuResult {
  status: number
  completed: number
  failed: number
  warning: number
  remaining: number
}

/**
 * Reads the full DICOM dataset as JSON. Mirrors plain `dcmnorm file.dcm`
 * (flat/name keys, bulk data as a URI reference, by default) or
 * `--format standard --keys hex --bulk-data inline`.
 */
export declare function readJson(filePath: string, options?: ReadJsonOptions | undefined | null): Promise<unknown>

export interface ReadJsonOptions {
  format?: string
  keyStyle?: string
  /**
   * 'uri' (default, matches the CLI) emits PixelData/other bulk elements as a
   * small "?offset=..&length=.." reference; 'inline' base64-embeds them, which
   * for a typical image is orders of magnitude larger.
   */
  bulkData?: string
}

export declare function readTags(filePath: string, tags: Array<string>): Promise<unknown>

export interface RenderedFrame {
  mimeType: string
  width: number
  height: number
  data: Buffer
}

export interface RenderedMovie {
  mimeType: string
  data: Buffer
}

/**
 * Renders a single frame of a DICOM file to JPEG or PNG. Mirrors `dcmnorm --output-width ...
 * --output-height ... --window-center ... --window-width ... --render-frame ... file.dcm out.jpg`.
 */
export declare function renderFrame(filePath: string, options?: RenderFrameOptions | undefined | null): Promise<unknown>

export interface RenderFrameOptions {
  /** 'jpeg' (default) or 'png'. */
  format?: string
  outputWidth?: number
  outputHeight?: number
  windowCenter?: number
  windowWidth?: number
  frameIndex?: number
  jpegQuality?: number
}

/**
 * Renders every frame of a multi-frame DICOM file to an MP4 (via a piped `ffmpeg` subprocess -
 * requires `ffmpeg` on `PATH`). Mirrors `dcmnorm --render-fps ... --output-width ... file.dcm out.mp4`.
 */
export declare function renderMovie(filePath: string, options?: RenderMovieOptions | undefined | null): Promise<unknown>

export interface RenderMovieOptions {
  outputWidth?: number
  outputHeight?: number
  windowCenter?: number
  windowWidth?: number
  /** Defaults to 24 (matching the CLI's default when the DICOM file itself specifies no frame rate). */
  fps?: number
}

/**
 * Starts a DICOM SCP (association acceptor) on `port` (0 picks an ephemeral port - see the
 * returned handle's `localPort`), answering C-ECHO, C-STORE, C-FIND, and C-MOVE. C-ECHO and
 * C-STORE are handled entirely natively (C-STORE writes each received instance under
 * `cachePath` as `S_<StudyInstanceUID>/<Modality>_<SOPInstanceUID>.dcm`); C-FIND, C-MOVE, and
 * "association complete" (fired once per association that stored at least one instance) are
 * delegated to the given `async function` callbacks:
 *
 * - `onFind(filterJson)` - `filterJson` has whichever of StudyInstanceUID/StudyDate/
 *   PatientName/PatientID keys the request's Identifier actually had values for. Must resolve
 *   to a JSON array of matched-study objects (whichever of StudyInstanceUID/AccessionNumber/
 *   PatientID/PatientName/PatientBirthDate/StudyDate/StudyTime/StudyDescription/
 *   ModalitiesInStudy/NumberOfStudyRelatedSeries/NumberOfStudyRelatedInstances each has).
 * - `onMove(studyInstanceUid, moveDestinationAe)` - must resolve to `"true"`/`"false"`
 *   (JSON-booleans-as-strings) indicating whether the move was successfully queued.
 * - `onAssociationComplete(storedInstancesByStudyJson)` - `storedInstancesByStudyJson` maps
 *   each StudyInstanceUID to the on-disk paths of every instance C-STORE'd for it during that
 *   association. Return value is ignored.
 *
 * Accepts every proposed presentation context regardless of abstract syntax - this is a
 * permissive "accept anything a real sender proposes" SCP, not a curated allow-list.
 */
export declare function startDicomServer(port: number, cachePath: string, aeTitle: string, maxPduLength: number | undefined | null, idleTimeoutMs: number | undefined | null, onFind: JsonCallback, onMove: TwoStringCallback, onAssociationComplete: JsonCallback): DicomServerHandle

/**
 * Sends each of `files` via C-STORE to `destination` ("host:port"). Resolves with one
 * `{sopInstanceUid, status}` per file that could be read and sent - a non-zero Status is just
 * data in the result (the peer rejected that instance), not a rejected Promise; this only
 * rejects if the association itself could not be established, or none of `files` could be read
 * as DICOM at all. `onLog`, if given, is called (synchronously, no return value expected) with a
 * debug line for each notable DIMSE event - association open/close, and each C-STORE-RQ/RSP.
 */
export declare function storeScu(destination: string, files: Array<string>, options?: StoreScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): Promise<unknown>

export interface StoreScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  maxPduLength?: number
  neverTranscode?: boolean
  /** Absolute ceiling (connect through release) for the whole call - not reset by activity. */
  timeoutMs?: number
}

export interface StoreScuResult {
  sopInstanceUid: string
  status: number
}

/**
 * Transcodes a DICOM file to the given transfer syntax UID. Mirrors
 * `dcmnorm --transfer-syntax UID in.dcm out.dcm`.
 */
export declare function transcode(filePath: string, outputPath: string, transferSyntaxUid: string): Promise<unknown>

/**
 * Writes a DICOM file from JSON (flat or standard format, auto never guessed -
 * pass the same `format` used to read it). Mirrors `dcmnorm dataset.json out.dcm`.
 * Sequence elements are always (re)written with undefined length, so this does
 * not carry forward stale defined-length byte counts from whatever encoding the
 * JSON was originally read from - see dicom_io::json's DataSetSequence handling.
 */
export declare function writeJson(json: string, outputPath: string, options?: WriteJsonOptions | undefined | null): Promise<unknown>

export interface WriteJsonOptions {
  format?: string
  /**
   * Resolves "?offset=..&length=.." BulkDataURIs (readJson's default 'uri'
   * bulkData mode emits these for bulk elements already in the source file)
   * against this file's bytes - mirrors the CLI's `--bulk-data-source`. Not
   * needed for InlineBinary or "file://" BulkDataURI elements, which are
   * self-contained and resolved independently of this option.
   */
  bulkDataSourcePath?: string
}
