/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Reports whether a file looks like valid DICOM. Mirrors `dcmnorm
 * --check-dicom`.
 */
export declare function checkDicom(filePath: string): Promise<unknown>

/**
 * Sets/removes DICOM attributes, optionally stripping private tags. Mirrors
 * `dcmnorm --set KEY=VALUE --remove KEY --remove-private-tags`. Writes back
 * to `file_path` in place unless `options.output_path` is given.
 */
export declare function editTags(filePath: string, options?: EditTagsOptions | undefined | null): Promise<unknown>

export interface EditTagsOptions {
  outputPath?: string
  set?: Record<string, string>
  remove?: Array<string>
  removePrivateTags?: boolean
}

/**
 * Reads the full DICOM dataset as JSON. Mirrors plain `dcmnorm file.dcm`
 * (flat/name keys, bulk data as a URI reference, by default) or
 * `--format standard --keys hex --bulk-data inline`.
 */
export declare function readJson(filePath: string, options?: ReadJsonOptions | undefined | null): Promise<unknown>

export interface ReadJsonOptions {
  format?: string
  keyStyle?: string
  /**
   * 'uri' (default, matches the CLI) emits PixelData/other bulk elements as a
   * small "?offset=..&length=.." reference; 'inline' base64-embeds them, which
   * for a typical image is orders of magnitude larger.
   */
  bulkData?: string
}

export declare function readTags(filePath: string, tags: Array<string>): Promise<unknown>

/**
 * Transcodes a DICOM file to the given transfer syntax UID. Mirrors
 * `dcmnorm --transfer-syntax UID in.dcm out.dcm`.
 */
export declare function transcode(filePath: string, outputPath: string, transferSyntaxUid: string): Promise<unknown>

/**
 * Writes a DICOM file from JSON (flat or standard format, auto never guessed -
 * pass the same `format` used to read it). Mirrors `dcmnorm dataset.json out.dcm`.
 * Sequence elements are always (re)written with undefined length, so this does
 * not carry forward stale defined-length byte counts from whatever encoding the
 * JSON was originally read from - see dicom_io::json's DataSetSequence handling.
 */
export declare function writeJson(json: string, outputPath: string, options?: WriteJsonOptions | undefined | null): Promise<unknown>

export interface WriteJsonOptions {
  format?: string
  /**
   * Resolves "?offset=..&length=.." BulkDataURIs (readJson's default 'uri'
   * bulkData mode emits these for bulk elements already in the source file)
   * against this file's bytes - mirrors the CLI's `--bulk-data-source`. Not
   * needed for InlineBinary or "file://" BulkDataURI elements, which are
   * self-contained and resolved independently of this option.
   */
  bulkDataSourcePath?: string
}
