/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DicomServerHandle {
  get localPort(): number
  /**
   * Stops accepting new associations and waits for the listener to shut down. Associations
   * already in progress finish independently (or hit their own idle timeout) - this does not
   * interrupt them. Safe to call more than once.
   */
  close(): void
}

export declare class DicomVolumeHandle {
  /** Rows in the source slices (image height). */
  get rows(): number
  /** Columns in the source slices (image width). */
  get cols(): number
  /** Number of slices in the built volume. */
  get numSlices(): number
  /**
   * The volume's own acquisition-native orientation, for seeding an "axial" reformat -
   * `[rowDir(3), colDir(3)]`.
   */
  get nativeBasis(): Array<number>
  /** The volume's own physical center, in patient/LPS mm - a reasonable default reformat origin. */
  get center(): Array<number>
  /** The volume's own smallest voxel dimension, in mm - a reasonable default output spacing. */
  get minSpacingMm(): number
  /**
   * Resamples one plane through this volume and encodes it exactly like a normal 2D render
   * (same `RenderedFrame` shape `renderFrame` returns), so callers can reuse their existing
   * image-display code path unchanged.
   */
  reformat(options: ReformatPlaneOptions): Promise<unknown>
  /**
   * Packs this volume's own NATIVE voxel lattice - not a resampled oblique plane, see
   * `exportTexture`'s own doc - as a lossless GPU-upload-ready texture payload (16-bit
   * samples, row-major, optionally gzip-compressed). Unlike `reformat()`, this is a one-shot
   * call per volume, not one per interaction: the render-server ships the returned `data`
   * once and the client does all further rotate/scroll/window-level manipulation itself in a
   * WebGL2 shader.
   */
  exportTexture(options?: ExportVolumeTextureOptions | undefined | null): Promise<unknown>
}

export declare class EchoScuHandle {
  /** The eventual Status code (0 = success), without requesting cancellation. */
  result(): Promise<number>
  /**
   * Requests a graceful A-RELEASE and resolves once the association has genuinely closed -
   * real acknowledgement, not a fire-and-forget signal. Idempotent.
   */
  release(): Promise<number>
  /**
   * Requests an immediate A-ABORT (no wait on the peer at all) and resolves once the
   * association has genuinely closed. Idempotent.
   */
  abort(): Promise<number>
}

export declare class FindScuHandle {
  /**
   * The eventual matched Identifiers (flat/hex-keyed DICOM JSON, one per match), without
   * requesting cancellation.
   */
  result(): Promise<Array<string>>
  /**
   * Requests a graceful A-RELEASE and resolves once the association has genuinely closed -
   * real acknowledgement, not a fire-and-forget signal. Idempotent.
   */
  release(): Promise<Array<string>>
  /**
   * Requests an immediate A-ABORT (no wait on the peer at all) and resolves once the
   * association has genuinely closed. Idempotent.
   */
  abort(): Promise<Array<string>>
}

export declare class MoveScuHandle {
  /**
   * The eventual terminal `MoveScuResult`, without requesting cancellation - for a caller
   * that just wants to await completion.
   */
  result(): Promise<MoveScuResult>
  /**
   * Requests a graceful A-RELEASE and resolves once the association has genuinely closed -
   * real acknowledgement, not a fire-and-forget signal that might land seconds later (or
   * never, if missed). Idempotent: a second call just observes the same outcome.
   */
  release(): Promise<MoveScuResult>
  /**
   * Requests an immediate A-ABORT (no wait on the peer at all) and resolves once the
   * association has genuinely closed. Idempotent.
   */
  abort(): Promise<MoveScuResult>
}

export declare class StoreScuHandle {
  /**
   * The eventual per-file `{sopInstanceUid, status}` results, without requesting
   * cancellation.
   */
  result(): Promise<Array<StoreScuResult>>
  /**
   * Requests a graceful A-RELEASE and resolves once the association has genuinely closed -
   * real acknowledgement, not a fire-and-forget signal. Idempotent.
   */
  release(): Promise<Array<StoreScuResult>>
  /**
   * Requests an immediate A-ABORT (no wait on the peer at all) and resolves once the
   * association has genuinely closed. Idempotent.
   */
  abort(): Promise<Array<StoreScuResult>>
}

/**
 * Builds a 3D volume from a parallel stack of DICOM slice files (e.g. every image instance in
 * one CT/MR/PT series) sharing consistent `ImageOrientationPatient`. Slices are spatially
 * re-sorted internally by `ImagePositionPatient`, regardless of `filePaths`' own order. Returns a
 * `DicomVolumeHandle` for repeated `reformat()` calls. Rejects (rather than silently
 * mis-rendering) fewer than 2 files, mismatched Rows/Columns, or a non-parallel/gantry-tilt-
 * inconsistent stack.
 */
export declare function buildVolume(filePaths: Array<string>): Promise<unknown>

/**
 * Reports whether a file looks like valid DICOM. Mirrors `dcmnorm
 * --check-dicom`.
 */
export declare function checkDicom(filePath: string): Promise<unknown>

/**
 * Computes a pixel-value histogram for every frame of a DICOM file (or just one, via
 * `options.frameIndex`). Mirrors `dcmnorm --histogram --histogram-bins ... file.dcm`.
 */
export declare function computeHistogram(filePath: string, options?: HistogramOptions | undefined | null): Promise<unknown>

/**
 * Performs a C-ECHO (DICOM Verification) against `destination` ("host:port"). Resolves with the
 * response Status code (0 = success); rejects only if the association itself could not be
 * established (unreachable host, no accepted presentation context, etc). `onLog`, if given, is
 * called (synchronously, no return value expected) with a debug line for each notable DIMSE
 * event - association open/close, the request sent, the response received.
 */
export declare function echoScu(destination: string, options?: EchoScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): Promise<unknown>

export interface EchoScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  timeoutMs?: number
}

/**
 * Sets/removes DICOM attributes, optionally stripping private tags. Mirrors
 * `dcmnorm --set KEY=VALUE --remove KEY --remove-private-tags`. Writes back
 * to `file_path` in place unless `options.output_path` is given.
 */
export declare function editTags(filePath: string, options?: EditTagsOptions | undefined | null): Promise<unknown>

export interface EditTagsOptions {
  outputPath?: string
  set?: Record<string, string>
  remove?: Array<string>
  removePrivateTags?: boolean
}

/**
 * Packs several independent frames (from one or more files) as one texture-array upload - see
 * `dcmnorm::dicom_io::pack_frame_stack_texture`'s own doc for the full contract (no resampling,
 * no cross-layer interpolation, no physical geometry). Mirrors `exportFrameTexture`'s
 * options/result shape, generalized to many sources.
 */
export declare function exportFrameStackTexture(sources: Array<FrameStackSource>, options?: ExportFrameStackTextureOptions | undefined | null): Promise<unknown>

export interface ExportFrameStackTextureOptions {
  /** 'gzip' (default) or 'none'. */
  compression?: string
  windowCenter?: number
  windowWidth?: number
}

/**
 * Packs a single frame's raw (unwindowed) physical values as a depth-1 "1-slice volume" texture
 * - lets a large diagnostic 2D image (e.g. DX/CR/mammography) reuse the exact same client GPU
 * texture/shader pipeline as an MPR volume, instead of the lossy zoomed-JPEG path `renderFrame`
 * produces. Mirrors `dcmnorm --render-frame ... --output-type texture file.dcm out.gputex`.
 */
export declare function exportFrameTexture(filePath: string, options?: ExportFrameTextureOptions | undefined | null): Promise<unknown>

export interface ExportFrameTextureOptions {
  /** Zero-based frame index for a multi-frame file. Defaults to 0. */
  frameIndex?: number
  targetMaxDim?: number
  /** 'gzip' (default) or 'none'. */
  compression?: string
  windowCenter?: number
  windowWidth?: number
}

export interface ExportVolumeTextureOptions {
  /**
   * Caps the longest of width/height/depth at this many samples, proportionally downsampling
   * (trilinear) if the native volume exceeds it. Omitted means no cap (full native
   * resolution) - the caller (render-server) is expected to derive this from the client's
   * reported `MAX_3D_TEXTURE_SIZE`, or from a small fixed value for a fast "progressive"
   * first pass ahead of the full-resolution texture.
   */
  targetMaxDim?: number
  /** 'gzip' (default) or 'none'. */
  compression?: string
  /**
   * Optional default window/level to carry through to `TextureExportResult.defaultWindowCenter`
   * /`defaultWindowWidth` - purely informational for the client's initial render, since the
   * exported samples themselves are never windowed.
   */
  windowCenter?: number
  windowWidth?: number
}

/**
 * Performs a C-FIND (Study Root Query/Retrieve) against `destination` ("host:port"). `query`
 * values: empty string is a universal-match "return key" (mirrors findscu's bare `-k TAG`),
 * non-empty constrains the match (mirrors `-k TAG=value`); `QueryRetrieveLevel` defaults to
 * `"STUDY"` if not given. Resolves with one flat/hex-keyed DICOM JSON string per match (parse
 * JS-side, same shape as `readJson({format: "flat", keyStyle: "hex"})`). `onLog`, if given, is
 * called (synchronously, no return value expected) with a debug line for each notable DIMSE
 * event - association open/close, and each C-FIND-RQ/RSP (query values are not logged, only the
 * tag keys queried, since the Identifier commonly carries PHI).
 */
export declare function findScu(destination: string, query: Record<string, string>, options?: FindScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): Promise<unknown>

export interface FindScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  maxPduLength?: number
  timeoutMs?: number
}

/** Mirrors `dcmnorm::dicom_io::FrameHistogram` for the JS side. */
export interface FrameHistogram {
  frameIndex: number
  binCount: number
  rangeMin: number
  rangeMax: number
  binWidth: number
  counts: Array<number>
  pixelCount: number
  minValue: number
  maxValue: number
  mean: number
  stdDev: number
}

export interface FrameStackSource {
  filePath: string
  /** Zero-based frame indices to include from this file, in order. Defaults to `[0]`. */
  frameIndices?: Array<number>
}

export interface HistogramOptions {
  /** Number of bins per frame histogram. Defaults to 256. */
  binCount?: number
  /** Compute only this zero-based frame's histogram, instead of every frame in the instance. */
  frameIndex?: number
  /**
   * Lower bound of the binned value range. Defaults to each frame's own observed minimum.
   * Must be set together with `maxValue`.
   */
  minValue?: number
  /**
   * Upper bound of the binned value range. Defaults to each frame's own observed maximum.
   * Must be set together with `minValue`.
   */
  maxValue?: number
}

/**
 * Performs a C-MOVE (Study Root Query/Retrieve), asking `destination` ("host:port") to push
 * `studyInstanceUid` to `moveDestinationAe` (an AE title `destination` already knows how to
 * reach, not a socket address). Returns a handle immediately - the retrieve itself runs on its
 * own background thread - rather than blocking until it reaches a terminal status; call
 * `.result()` to await that terminal status and sub-operation counts (regardless of
 * success/warning/failure, mirroring the old behavior), or `.release()`/`.abort()` to close it
 * early once some other signal (e.g. the study already being confirmed fully received via a
 * separate channel) makes further waiting pointless. See `MoveScuHandle`.
 *
 * `onLog`, if given, is called (synchronously, no return value expected) with a debug line for
 * each notable DIMSE event - association open/close, and each C-MOVE-RQ/RSP (including every
 * pending response, so a slow multi-instance move is visible sub-operation by sub-operation).
 */
export declare function moveScu(destination: string, moveDestinationAe: string, studyInstanceUid: string, options?: MoveScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): MoveScuHandle

export interface MoveScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  maxPduLength?: number
  /** Absolute ceiling (connect through release) for the whole call - not reset by activity. */
  timeoutMs?: number
  /**
   * Directory to watch for local write progress (e.g. this retrieve's own cache destination)
   * - see `staleDataTimeoutMs`. Both must be set for the watch to run.
   */
  watchPath?: string
  /**
   * How long `watchPath` may go without a new/modified file before the connection is
   * considered stale and aborted - independent of, and typically much shorter than,
   * `timeoutMs`.
   */
  staleDataTimeoutMs?: number
}

export interface MoveScuResult {
  status: number
  completed: number
  failed: number
  warning: number
  remaining: number
  cancelled: boolean
  /**
   * `"release"`/`"abort"` when `cancelled` is true, indicating which teardown verb actually
   * produced it (see `MoveScuHandle.release`/`.abort`) - `null` for a real terminal C-MOVE-RSP.
   */
  cancelledVia?: string
}

/** Mirrors `dcmnorm::dicom_io::OverlaySummary` for the JS side. */
export interface OverlaySummary {
  index: number
  group: number
  rows: number
  columns: number
  overlayType?: string
  label?: string
}

/**
 * Reads the full DICOM dataset as JSON. Mirrors plain `dcmnorm file.dcm`
 * (flat/name keys, bulk data as a URI reference, by default) or
 * `--format standard --keys hex --bulk-data inline`.
 */
export declare function readJson(filePath: string, options?: ReadJsonOptions | undefined | null): Promise<unknown>

export interface ReadJsonOptions {
  format?: string
  keyStyle?: string
  /**
   * 'uri' (default, matches the CLI) emits PixelData/other bulk elements as a
   * small "?offset=..&length=.." reference; 'inline' base64-embeds them, which
   * for a typical image is orders of magnitude larger.
   */
  bulkData?: string
}

export declare function readTags(filePath: string, tags: Array<string>): Promise<unknown>

export interface ReformatPlaneOptions {
  /** World-space (mm, patient/LPS) point at the CENTER of the reformatted output image. */
  origin: Array<number>
  /** Unit vector: direction of travel across the output image as the column index increases. */
  rowDir: Array<number>
  /** Unit vector: direction of travel down the output image as the row index increases. */
  colDir: Array<number>
  outputWidth: number
  outputHeight: number
  /** Physical size of one output pixel, in mm - the same in both output axes. */
  spacingMm: number
  windowCenter?: number
  windowWidth?: number
  /** 'jpeg' (default) or 'png'. */
  format?: string
  jpegQuality?: number
  /**
   * 'trilinear' (default) or 'nearest' - nearest is faster and intended for a live-drag
   * preview frame, trilinear for the settled/idle frame.
   */
  interpolation?: string
  /**
   * Total slab thickness in mm, centered on `origin` along the plane's own normal. Omitted or
   * 0 reformats an infinitely-thin plane (the original single-voxel-thick MPR behavior).
   */
  slabThicknessMm?: number
  /**
   * How the slab's samples combine when `slabThicknessMm > 0`: 'mip' (default, maximum
   * intensity projection), 'minip' (minimum intensity projection), or 'average'.
   */
  slabProjection?: string
}

export interface RenderedFrame {
  mimeType: string
  width: number
  height: number
  data: Buffer
  /**
   * All overlay planes present on the source instance, regardless of whether one was
   * rendered into `data`.
   */
  overlays: Array<OverlaySummary>
  /** Which overlay (by `OverlaySummary.index`) was actually composited into `data`, if any. */
  selectedOverlayIndex?: number
}

export interface RenderedMovie {
  mimeType: string
  data: Buffer
}

/**
 * Renders a single frame of a DICOM file to JPEG or PNG. Mirrors `dcmnorm --output-width ...
 * --output-height ... --window-center ... --window-width ... --render-frame ... file.dcm out.jpg`.
 */
export declare function renderFrame(filePath: string, options?: RenderFrameOptions | undefined | null): Promise<unknown>

export interface RenderFrameOptions {
  /** 'jpeg' (default) or 'png'. */
  format?: string
  outputWidth?: number
  outputHeight?: number
  windowCenter?: number
  windowWidth?: number
  frameIndex?: number
  jpegQuality?: number
  /**
   * Whether to composite an overlay plane, when the instance has one. Defaults to `true` -
   * the first available overlay renders by default.
   */
  showOverlays?: boolean
  /**
   * Which overlay to render, by its 0-based `OverlaySummary.index`. Defaults to the first
   * available overlay. Ignored when `showOverlays` is `false`.
   */
  overlayIndex?: number
  /** Fill color for rendered overlay pixels, as `"#RRGGBB"` or `"R,G,B"`. Defaults to green. */
  overlayColor?: string
}

/**
 * Renders every frame of a multi-frame DICOM file to an MP4 (via a piped `ffmpeg` subprocess -
 * requires `ffmpeg` on `PATH`). Mirrors `dcmnorm --render-fps ... --output-width ... file.dcm out.mp4`.
 */
export declare function renderMovie(filePath: string, options?: RenderMovieOptions | undefined | null): Promise<unknown>

export interface RenderMovieOptions {
  outputWidth?: number
  outputHeight?: number
  windowCenter?: number
  windowWidth?: number
  /** Defaults to 24 (matching the CLI's default when the DICOM file itself specifies no frame rate). */
  fps?: number
}

/**
 * Starts a DICOM SCP (association acceptor) on `port` (0 picks an ephemeral port - see the
 * returned handle's `localPort`), answering C-ECHO, C-STORE, C-FIND, and C-MOVE. C-ECHO and
 * C-STORE are handled entirely natively (C-STORE writes each received instance under
 * `cachePath` as `S_<StudyInstanceUID>/<Modality>_<SOPInstanceUID>.dcm`); C-FIND, C-MOVE, and
 * "association complete" (fired once per association that stored at least one instance) are
 * delegated to the given `async function` callbacks:
 *
 * - `onFind(filterJson)` - `filterJson` has whichever of StudyInstanceUID/StudyDate/
 *   PatientName/PatientID keys the request's Identifier actually had values for. Must resolve
 *   to a JSON array of matched-study objects (whichever of StudyInstanceUID/AccessionNumber/
 *   PatientID/PatientName/PatientBirthDate/StudyDate/StudyTime/StudyDescription/
 *   ModalitiesInStudy/NumberOfStudyRelatedSeries/NumberOfStudyRelatedInstances each has).
 * - `onMove(studyInstanceUid, moveDestinationAe)` - must resolve to `"true"`/`"false"`
 *   (JSON-booleans-as-strings) indicating whether the move was successfully queued.
 * - `onAssociationComplete(storedInstancesByStudyJson)` - `storedInstancesByStudyJson` maps
 *   each StudyInstanceUID to the on-disk paths of every instance C-STORE'd for it during that
 *   association. Return value is ignored.
 *
 * `onLog`, if given, is called (fire-and-forget, from whichever connection thread is handling
 * the association at the time) with a debug-detail line per association accept/negotiation,
 * each request/response, and release/abort - the SCP-side counterpart of `onLog` on
 * `echoScu`/`storeScu`/`findScu`/`moveScu`.
 *
 * Accepts every proposed presentation context regardless of abstract syntax - this is a
 * permissive "accept anything a real sender proposes" SCP, not a curated allow-list.
 */
export declare function startDicomServer(port: number, cachePath: string, aeTitle: string, maxPduLength: number | undefined | null, idleTimeoutMs: number | undefined | null, onFind: JsonCallback, onMove: TwoStringCallback, onAssociationComplete: JsonCallback, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): DicomServerHandle

/**
 * Same as `echoScu`, but returns immediately with a handle instead of blocking until the
 * C-ECHO completes - lets a caller `abort()`/`release()` it early. See `EchoScuHandle`.
 */
export declare function startEchoScu(destination: string, options?: EchoScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): EchoScuHandle

/**
 * Same as `findScu`, but returns immediately with a handle instead of blocking until the
 * C-FIND completes - lets a caller `abort()`/`release()` it early. See `FindScuHandle`.
 */
export declare function startFindScu(destination: string, query: Record<string, string>, options?: FindScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): FindScuHandle

/**
 * Same as `storeScu`, but returns immediately with a handle instead of blocking until every
 * file has been sent - lets a caller `abort()`/`release()` it early. See `StoreScuHandle`.
 */
export declare function startStoreScu(destination: string, files: Array<string>, options?: StoreScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): StoreScuHandle

/**
 * Sends each of `files` via C-STORE to `destination` ("host:port"). Resolves with one
 * `{sopInstanceUid, status}` per file that could be read and sent - a non-zero Status is just
 * data in the result (the peer rejected that instance), not a rejected Promise; this only
 * rejects if the association itself could not be established, or none of `files` could be read
 * as DICOM at all. `onLog`, if given, is called (synchronously, no return value expected) with a
 * debug line for each notable DIMSE event - association open/close, and each C-STORE-RQ/RSP.
 */
export declare function storeScu(destination: string, files: Array<string>, options?: StoreScuOptions | undefined | null, onLog?: (((err: Error | null, arg: string) => any)) | undefined | null): Promise<unknown>

export interface StoreScuOptions {
  callingAeTitle?: string
  calledAeTitle?: string
  maxPduLength?: number
  neverTranscode?: boolean
  /** Absolute ceiling (connect through release) for the whole call - not reset by activity. */
  timeoutMs?: number
}

export interface StoreScuResult {
  sopInstanceUid: string
  status: number
}

export interface TextureExportResult {
  /** 'volume' or 'image2d'. */
  contentKind: string
  /** 'int16' or 'uint16'. */
  sampleFormat: string
  /** 'none' or 'gzip' - matches how `data` below is actually encoded. */
  compression: string
  /**
   * `false` means `data` is a bounded-error quantization (see `rescaleSlope`/
   * `rescaleIntercept`), not an exact round-trip of the source samples.
   */
  lossless: boolean
  width: number
  height: number
  /** Always 1 for `contentKind: 'image2d'`. */
  depth: number
  /** `texel * rescaleSlope + rescaleIntercept` recovers the physical value (e.g. HU). */
  rescaleSlope: number
  rescaleIntercept: number
  rowSpacingMm: number
  colSpacingMm: number
  /** `0` for `contentKind: 'image2d'`. */
  sliceSpacingMm: number
  /** `[x, y, z]`, LPS mm, center of voxel (0,0,0). */
  origin: Array<number>
  rowDir: Array<number>
  colDir: Array<number>
  normalDir: Array<number>
  defaultWindowCenter?: number
  defaultWindowWidth?: number
  nativeWidth: number
  nativeHeight: number
  nativeDepth: number
  downsampled: boolean
  /**
   * Uncompressed byte length of `data`'s content - an exact integer, safely representable as
   * `f64` at any real texture size (well under 2^53).
   */
  payloadBytesRaw: number
  /**
   * `data.length` - included on the result too (not just derivable from `data` client-side)
   * so the render-server can log/cap transfer size without touching the buffer itself.
   */
  payloadBytesStored: number
  data: Buffer
}

/**
 * Transcodes a DICOM file to the given transfer syntax UID. Mirrors
 * `dcmnorm --transfer-syntax UID in.dcm out.dcm`.
 */
export declare function transcode(filePath: string, outputPath: string, transferSyntaxUid: string): Promise<unknown>

/**
 * Writes a DICOM file from JSON (flat or standard format, auto never guessed -
 * pass the same `format` used to read it). Mirrors `dcmnorm dataset.json out.dcm`.
 * Sequence elements are always (re)written with undefined length, so this does
 * not carry forward stale defined-length byte counts from whatever encoding the
 * JSON was originally read from - see dicom_io::json's DataSetSequence handling.
 */
export declare function writeJson(json: string, outputPath: string, options?: WriteJsonOptions | undefined | null): Promise<unknown>

export interface WriteJsonOptions {
  format?: string
  /**
   * Resolves "?offset=..&length=.." BulkDataURIs (readJson's default 'uri'
   * bulkData mode emits these for bulk elements already in the source file)
   * against this file's bytes - mirrors the CLI's `--bulk-data-source`. Not
   * needed for InlineBinary or "file://" BulkDataURI elements, which are
   * self-contained and resolved independently of this option.
   */
  bulkDataSourcePath?: string
}
